nelmio_cors:
    paths:
        '^/': ~
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:8080']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
